/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Typicons, (c) Stephen Hutchings 2012
///         Author:    Stephen Hutchings
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://typicons.com/
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Fontelico, Copyright (C) 2012 by Fontello project
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://fontello.com
/// * Linecons, Copyright (C) 2013 by Designmodo
///         Author:    Designmodo for Smashing Magazine
///         License:   CC BY ()
///         Homepage:  http://designmodo.com/linecons-free/
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const String? _kFontPkg = null;

  static const IconData users_outline = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_circled = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_black = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData avatar = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData users = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_balance = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData adjust = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle_outline = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apps = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData content_copy = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData done_all = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData forum = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_add = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData library_books = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData all_inclusive = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_happy = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emo_unhappy = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star_empty = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_alt = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_list = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_large_outline = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData th_outline = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tags = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookmark = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_1 = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper_plane = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData globe = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog_1 = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData params = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData note = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData search = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail_1 = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_1 = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond_1 = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData creative_commons = IconData(0xf25e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData teamspeak = IconData(0xf4f9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
